### ISSUE TITLE
☂️ Getting gardener-extension-shoot-rsyslog-relp production ready

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener-extension-shoot-rsyslog-relp#2]
**What would you like to be added**:
/area security audit-logging
/kind task

**What would you like to be added**:
Tasks to make the gardener-extension-shoot-rsyslog-relp production ready.

**Why is this needed**:
Getting the shoot-rsyslog-relp extension production ready.

## Steps

- [x] Add prow jobs to execute checks and tests, validate PRs and manage releases: https://github.com/gardener/ci-infra/pull/857. @plkokanov
- [x] Use `skaffold` to deploy the extension when developing locally instead of the [rsyslog-relp-up-kind.sh](https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/blob/d59c9bccf67d4ed9ae827338748e8ea57bf8ec69/Makefile#L137-L139) script: https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/5
- [x] https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/issues/12
- [x] https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/issues/16 https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/19
- [x] Add monitoring config for rsyslog (and auditd) to prometheus in shoot control plane 
  - [x] The `node-exporter` can be reused if its textfile collector is enabled. The metrics from rsyslog can be transformed by a script so that they are in a format that `node-exporter` accepts and then written to a `*.prom` file which can be read by the textfile collector.
    - [x] Prepare a POC and sync it with Istvan https://github.com/plkokanov/gardener-extension-shoot-rsyslog-relp/tree/poc/prometheus-metrics
    - [x] Enable the `textfile-collector` of the `node-exporter` in g/g https://github.com/gardener/gardener/pull/8721
    - [x] Expose rsyslog metrics via node-exporter's textfile collector and display them in a dedicated plutono dashboard https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/32
  -  Two other options currently have been evaluated, but for now the textfile seems better: 
        1.Possibly explore how metrics are exposed via https://github.com/prometheus-community/rsyslog_exporter
        2. A different option would be to reuse a scraper running on the node which simply reads from the `/var/log/rsyslog-stats.log` to which rsyslog is configured to write metrics.
- [x] Add logging config for rsyslog (and auditd) to `vali` in shoot control plane
- [x] Build binaries from PRs with prow instead of concourse.
    - https://github.com/gardener/ci-infra/pull/1037 
    - https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/38
- [x] Tests
  - [x] Add e2e tests: https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/7
  - [x] Add e2e tests with TLS communication to the relp target server enabled https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/27
  - [x] Add testmachinery tests #52 
  - [x] Add integration test for the rsyslog-relp shoot admission webhook
  - [x] https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/issues/26 https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/34
  - [x] https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/issues/35
- [x] Go through the [component-checklist](https://github.com/gardener/gardener/blob/master/docs/development/component-checklist.md) in gardener/gardener and double-check every item. https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/29
  - [x] Remove the helm charts that are currently used to deploy `rsyslog-relp-configurator` and `rsyslog-relp-configuration-cleaner` ManagedResources. https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/48
  - [x] Use unique configmaps and secrets - will be indirectly handled by #41 
  - [x] Define `RBAC` roles with minimal privileges
  - [x] Do not run components in privileged mode
  - [x] Choose the proper `Seccomp` profile
  - [x] Define `PodSecurityPolicy`s
  - [x] Specify the component type label for high availability
  - [x] Check if PodDisruptionBudget is configured correctly
  - [x] Provide resource requirements
  - [x] Check VPA and HPA settings
  - [x] Define health checks - Shoot system components are automatically checked via their respective [ManagedResource conditions](https://github.com/gardener/gardener/blob/master/docs/concepts/resource-manager.md#managedresource-controller) so the `helathcheck` controller and checks is no-longer necessary. https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/28
  - [x] Remove unnecessary checks for kubernetes versions that are no longer supported from charts
- [x] Similar to https://github.com/gardener/gardener-extension-registry-cache/pull/83 we can remove the deployment of the special `rsyslog-relp-configuration-cleaner` ManagedResource responsible to clean-up the rsyslog and audit configuration from the node if the shoot is currently being deleted, thus speeding up deletion. https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/30
- [x] Cleanup and restructure `examples` directory of unnecessary files. Now that we only support the local setup based on gardener's local setup, most of the files are not needed. https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/39
  - [x] Generate the CRDs used for the integration test once the issue described in https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/39/files#r1422706214 is resolved. https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/72
- [x] Use the `hack/check-skaffold-deps-for-binary.sh` from Gardener scripts. Similar to https://github.com/gardener/gardener-extension-registry-cache/pull/97/commits/09e61ff3878f76b0af1518b142a51b8f4be9b350
- [x] Update development documentation once https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/41 is merged: https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/56
- [x] Replace the DaemonSet approach by OperatingSystemConfig mutating webhook. The webhook adds  configuration files under `/etc/rsyslog.d` and necessary secrets for the RELP communication from rsyslog to the target server. Uninstallation can still be done via a daemonset (reusing the rsyslog-relp-configuration-cleaner). #41 
    - [x] Enforce the referenced secret, which is used for the tls connection, deployed in the shoot's project namespace to be `immutable` and remove the secondary validation for this secret which is currently done in the OSC mutating webhook. Once the secret is `immutable` users will have to create a new object to "update" it's contents and change the corresponding entry in the `shoot.spec.resources[]` array. This will trigger the shoot validation part of the `shoot-rsyslog-relp-admission` and thus also validate the new secret: https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/76
- [x] Ensure that `rsyslog.service` is enabled on all operating systems https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/58
- [x] Currently the rsyslog-relp extension also configures auditd as the rules are not properly configured on all `gardenlinux` versions. It deploys preset audit rules. This deployment of rules should be made optional and the rules themselves configurable. https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/49
- [x] Drop support for kubernetes v1.24: https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/79
- [x] Avoid log duplication: Only enable the `audispd` plugin to forward logs to journald, if the `systemd-journald-audit.socket` socket is missing. If the socket is present, then audit logs are automatically gathered by `journald`. https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/104
- [x] Make it easier and add documentation on how to create a development environment when [Deploying Gardener Locally and Enabling Provider-Extensions] https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/102(https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally_with_extensions.md)
- [x] Replace usages of deprecated pointer functions similar to https://github.com/gardener/gardener/pull/9107 https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/73
- [x] Reuse [these functions from the `gardener/extensions` pakage](https://github.com/gardener/gardener/blob/8e3152a87b83b5db7cf3203698963146bb98bf9d/extensions/pkg/webhook/utils.go#L301C25-L323)  to merge additional `extensions.Files` and `extensions.Units` while mutating `OperatingSystemConfig` resources. https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/73
- [x] 🚦 Release `shoot-rsyslog-relp` extension `v0.4.0` 
    - [x] 🟢  (Release Blocker) There is an issue with the `rsyslogd` process on nodes running gardenlinux `1312.3` which prevents it from reading the certificate files required to initialise a TLS connection to the target RELP server. The `rsyslog` process also seems to not have access to the `process_rsyslog_stats.sh` script and therefore cannot use it write metrics in the `/var/lib/node-exporter/textfile-collector` directory:
        ```
        Mar 12 16:02:38 ip-10-180-29-39.eu-west-1.compute.internal rsyslogd[688629]: error: certificate file /var/lib/rsyslog-relp-configurator/tls/ca.crt couldn't be accessed: Permission denied  [v8.2310.0 try https://www.rsyslog.com/e/2039 ]
        Mar 12 16:02:38 ip-10-180-29-39.eu-west-1.compute.internal rsyslogd[688629]: error: certificate file /var/lib/rsyslog-relp-configurator/tls/tls.crt couldn't be accessed: Permission denied  [v8.2310.0 try https://www.rsyslog.com/e/2039 ]
        Mar 12 16:02:38 ip-10-180-29-39.eu-west-1.compute.internal rsyslogd[688629]: error: certificate file /var/lib/rsyslog-relp-configurator/tls/tls.key couldn't be accessed: Permission denied  [v8.2310.0 try https://www.rsyslog.com/e/2039 ]
        ...
        ...
        Mar 12 16:03:38 ip-10-180-29-39.eu-west-1.compute.internal rsyslogd[688629]: omprog: failed to execute program '/var/lib/rsyslog-relp-configurator/process-rsyslog-pstats.sh': Permission denied
        ```
        This issue only occurs on gardenlinx `1312.3` when the mentioned files are added via the `OSC` mutation added by #41. It does not occur on previous gardenlinux versions and it does not occur if the `rsyslog-relp-configurator` daemonset is used. Gardenlinux colleagues have been notified about this and we are jointly investigating it.
    - [x] 🟢After closer investigation we saw that the new gardenlinux version comes with an updated rsyslog version for which the `CAP_DAC_OVERRIDE` capability is dropped. Additionally, the `gardener-node-agent` creates directories for files on the host without any permissions. This leads to processes that do not have `CAP_DAC_OVERRIDE` to fail to read files in such directories. Issues has been opened on g/g: https://github.com/gardener/gardener/issues/9424
    - [x] Increase test timeouts for `testmachinery` tests #82 
    - [x] validate new release
- [x] The `shoot-rsyslog-relp-prometheus-*` configmap used for monitoring config could cause prometheus to `CrashLoopBackOff` after version updates: https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/issues/89
- [x] https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/issues/4
- [x] https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/106
- [x] ~✨**Nice to have:** support multiple targets. Scenario: collect logs from node bootstrapping in a dedicated server to debug node creation failures (moved as separate issue)~
- [x] ✨**Nice to have:** enable renovate or dependabot for gardener updates https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/87

**Comment by ialidzhikov** [comment]
All subtasks are completed. 🎉 

/close
